name: Blendedlearning

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  test:
    name: Run unit tests
    needs: build  # Ensure this job runs only after 'build' job is completed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout your repository code

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Corrected action for setting up Docker Buildx

      - name: Run ESLint
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/backend_nestjs
          run: sh -c "npm run lint"

      - name: Run tests
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/backend_nestjs
          run: sh -c "npm run test"

  deploy:
    needs: test  # Change this to 'test' to ensure deployment happens after tests pass
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout your repository code

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          token: ${{ secrets.TOKEN }}
          folder: dist
          branch: gh-pages

      - name: Deploy success
        run: echo "Deployed OK!"
