name: Blendedlearning

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile 
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/backend_nestjs:latest
          target: build

#  test:
#    name: Run unit tests
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - name: Run prettier
#        uses: docker/setup-buildx-action@v2
#
#      - name: Run ESLint
#        uses: addnab/docker-run-action@v3
#        with:
#          image: ${{ secrets.DOCKER_USERNAME }}/backend_nestjs
#          run: sh -c "npm run lint"
#
#      - name: Run tests
#        uses: addnab/docker-run-action@v3
#        with:
#          image: ${{ secrets.DOCKER_USERNAME }}/backend_nestjs
#          run: sh -c "npm run test"
#
#  deploy:
#    needs: build
#    runs-on: ubuntu-latest
#    permissions:
#      contents: write
#    steps:
#      - name: Deploy to GitHub Pages
#        uses: JamesIves/github-pages-deploy-action@v4.3.3
#        with:
#          token: ${{ secrets.TOKEN }}
#          folder: dist
#          branch: gh-pages
#
#      - name: Deploy success
#        run: echo "Deployed OK!"
